[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
kausamemory_head = "4VfiKtC5LXu5R72gKR9UwtRcFJ21uQsSMDSyTiAWdjR4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/kausalayer-vps-wallet.json"

[scripts]
